### ISSUE TITLE
Timeline shows wrong time since events happened

### ISSUE THREAD

**Issue by dror3go** [babybuddy/babybuddy#648] opened 2023-05-22 17:37 UTC
Starting at version 1.16.0 - viewing the timeline shows values like "-1 years, 11 months ago" for events that happened in the past several hours.
For example, I ended a timer and marked it as sleep, and in the timeline it shows as "-1 years, 11 months ago" even though it ended 1 minute ago.

I couldn't find an existing issue/discussion about this - which leaves me hanging.
I'm using LSIO - not sure if that's related.
Any ideas what to look for?

**Comment by MrApplejuice** [comment] 2023-05-24 13:03
I would guess that when you look at the database entries, you might get a hint what is going on.

![image](https://github.com/babybuddy/babybuddy/assets/542105/de4af89b-54b0-4b84-8e37-c0e08a459518)

Check the time entries (here from my own test database):

![image](https://github.com/babybuddy/babybuddy/assets/542105/501b7165-8916-4fce-8168-542f00d80aa4)

You might get a hint form there

**Comment by dror3go** [comment] 2023-05-24 18:31
Nope, that seems fine.

Note that the only place (at least from what I've seen) showing wrong information is the timeline: browsing the changes, feedings and sleep pages all show correct times, eg `Today, 8:03 p.m.`.
Also, the timeline itself is showing this weird information only for the first few records. Scrolling a bit and it seems OK.

**Comment by dror3go** [comment] 2023-05-25 17:16
OK I got it: the entries that show weird "time since" are those in the past 3 hours, which is the difference between my local time zone and UTC.
If recent releases changed something with the handling of time zones - this must be it.

**Comment by MrApplejuice** [comment] 2023-05-25 17:31
That sounds like very good input and something that _should_ be fixed. I tried to debug this on my personal test-server that is tracking `main`, but still cannot reproduce it:

![image](https://github.com/babybuddy/babybuddy/assets/542105/d73d3d54-2faa-4ced-957d-1ea8da9e6027)

I cannot quite tell what is going on, sorry, I think I need to leave this to someone who knows baby buddy better than me!

**Comment by MrApplejuice** [comment] 2023-05-25 20:30
I am in Europe/Amsterdam. I tried to change it to something like North America/"something-pacific-time" - could not replicate it.

One thing that came to mind: Do you know if the server you use to run Baby Buddy is using UTC or is it configured to use some other timezone? Something like that could maybe be untested? Hard for me to replicate without messing up my own system here or going through extra lengths setting up a VM...

**Comment by cdubz** [comment] 2023-05-27 15:13
> Starting at version 1.16.0 [...]

What version did you update _from_? I don't think anything happened between [v1.15.1 and v1.16.0](https://github.com/babybuddy/babybuddy/compare/v1.15.1...v1.16.0) that would impact dashboard time calculations.

**Comment by dror3go** [comment] 2023-05-27 19:00
I'm not really sure. I know I've updated after several months, but can't say for sure.
Is there a way for me to know which version was previously in use?

**Comment by cdubz** [comment] 2023-05-30 15:23
@dror3go there is no way out-of-the-box to know the previous version you were using.

> OK I got it: the entries that show weird "time since" are those in the past 3 hours, which is the difference between my local time zone and UTC.
If recent releases changed something with the handling of time zones - this must be it.

Following this thread...

1. What TZ do you have set for for your user?
2. What is the `TIME_ZONE` env set to for LSIO?
3. What TZ is the server set to (don't think this should be relevant but just in case)?

**Comment by dror3go** [comment] 2023-05-31 17:23
@cdubz All three are `Asia/Jerusalem` (which is UTC+3 at the moment). Note that LSIO's env name is `TZ`, not `TIME_ZONE`.
I didn't change any of these, and was running Babybuddy with no issues for the past ~8 months.

**Comment by 1v0dev** [comment] 2023-06-02 07:24
I have the same issue. My time zone is in Europe too. Only the last few entries in the timeline show this wrong time, previous entries are fine.

**Comment by cdubz** [comment] 2023-06-02 15:01
Ok, thank you both for the info. I haven't been able to confirm this yet but it certainly sounds like _something_ is up.

@1v0dev were you also _not_ experiencing this issue initially? If so do you happen to know what version you update from and to when it started happening?

**Comment by 1v0dev** [comment] 2023-06-04 09:25
Yes, it worked fine initially. Unfortunately, I don't know the exact version of it broke, but it was in the last 2 months. 

Here is a screenshot I took at 12.20 local time. Once certain amount of time pass, they start displaying the correct times, so it should be something with the display of the entries and not the database. 
![image](https://github.com/babybuddy/babybuddy/assets/56637685/4d521798-a074-4791-92fc-5f3ae3c461d7)

**Comment by cdubz** [comment] 2023-06-05 00:51
Does anyone have the ability to easily test this issue in https://github.com/babybuddy/babybuddy/releases/tag/v2.0.0-beta2? Just curious if it's already addressed there as it has lots of timezone handling changes...

**Comment by cdubz** [comment] 2023-06-15 03:04
I'm not able to reproduce this with the latest changes for the 2.0.x work so I'm going to tentatively close this. If anyone can reproduce in a 2.0.x version please do follow up and we'll reopen and investigate.

**Closed by cdubz** 2023-06-15 03:04 UTC
Labels: bug

**Comment by guillaumemichel** [comment] 2023-07-31 07:19
I used to experience the same problem, upgrading to 2.0.4 (from 1.16) seems to fix it.
