### ISSUE TITLE
"Time since" using Django time zone and not user time zone

### ISSUE THREAD

**Issue by puffnfresh** [babybuddy/babybuddy#178] opened 2020-12-27 01:21 UTC
The default time zone for Baby Buddy is UTC which I didn't change. I changed the time zone in my user profile to Australia/Hobart (UTC+11) which mostly worked for tracking feeds, etc.

The dashboard showed "0 days since last feed" because my feed time (UTC+11) was more recent than what Django saw as the current time (UTC)

Need to update `timesince` filters in the dashboard templates to work relative to the user's time zone.

**Comment by puffnfresh** [comment] 2020-12-27 01:24
Changing TIME_ZONE in the configuration to the same in my user profile makes the dashboard work fine, but if I have multiple users across time zones, it'd be wrong.

What's the point of having a time zone in the user profile? My opinion is Baby Buddy is so specific that most users on a server would probably be within a single time zone.

**Comment by cdubz** [comment] 2020-12-27 01:42
#113 and #118 give the history on time zone setting. The goal was just to allow it to be set from the UI easily. It is only associated with the user because that there was already a user settings construct and I figured why not 🤷‍♂️

**Comment by BenjaminHae** [comment] 2021-10-09 17:55
How about handling timestamps on the server side always in UTC, even in server requests/responses and doing localization using javascript?
That way a user does not need to setup anything, as the timezone is handled by the browser.

**Comment by BenjaminHae** [comment] 2021-10-10 09:40
> @BenjaminHae that may be doable… the server already does everything in UTC but I wonder if a client side TZ approach will for things like aggregated dashboard data and graphs? A lot of stuff happens server side for those things.

I think a lot of the logic needs to happen on the client side for that stuff.
Not a big problem, but a lot of work.

**Comment by cdubz** [comment] 2021-10-10 13:28
Yeah that would be a pretty big blocker to this ticket (:

**Comment by cdubz** [comment] 2022-02-26 21:38
Closing as I'm not able to reproduce this. The `timesince` filter is timezone-aware and this appears to be working as expected.

**Closed by cdubz** 2022-02-26 21:38 UTC
Labels: bug, good first issue
