### ISSUE TITLE
Last Feeding - 0 Days

### ISSUE THREAD

**Issue by foxalerts23** [babybuddy/babybuddy#181] opened 2020-12-31 19:54 UTC
The last feeding card on the dashboard recently stopped displaying hours and minutes since the last feeding and now shows 0 days.

**Comment by cdubz** [comment] 2021-01-01 16:48
Hm, I don't think there have been any (intentional) updates to the last feeding functionality in a while. The demo instance is at v1.4.0 and doesn't seem to have this issue. I'll get that updated to the tip to see if it can be reproduced there.

Does the card just always say 0 days for you? Do you recall when it started happening (and e.g. what version you may have updated from and to)?

**Comment by phooged** [comment] 2021-01-02 09:32
I have the same problem, only it says 0 days on all cards. When I restart the docker it works for a few hours, showing X hours X minutes ago. 
I'm on CET time zone and 24 hour format, if that is relevant?

Thanks for an awesome app by the way!

Cheers

**Comment by cdubz** [comment] 2021-01-02 14:38
Hmmm, how bizarre. I can't repro this in the demo -- I was thinking maybe if the last entry is older than 24 hours it may cause this, but it works in the demo app. Maybe this is something specific to Docker, but that seems unlikely... @foxalerts23 @phooged does everything else seemingly work correctly? E.g. datetime entries and data and graphs?

It would be helpful to get more information about your setups. E.g. what your docker compose file looks like (if you're using that) and what DB you're using? If you're on the `latest` tag it would be useful to know if you are able to revert to the `version-1.4.1` or `version-1.4.0` tag to see if the bug is in either of those as well.

Otherwise, some repro steps I could follow would be really helpful.

**Comment by phooged** [comment] 2021-01-02 15:02
I used the deployment instructions from the documentation: 
 ` wget -O docker-compose.yml https://raw.githubusercontent.com/babybuddy/babybuddy/master/docker-compose.example.yml
`
I'm running it on a digital ocean Ubuntu droplet.
Apart from the 24 hour format, I didn't change any settings.

> I was thinking maybe if the last entry is older than 24 hours it may cause this.
I don't think so, it happens with a clean install within 1 - 2 hours. 

Anything else I can provide you with? maybe the database export or something?

I'll have a poke around the demo, see if I can reproduce it there.

**Comment by cdubz** [comment] 2021-01-02 15:49
@phooged could you try disabling the 24 hour setting and see if that is the cause? I don’t think I’ve tested that in a while. I would test my self but busy chasing around two babies of my own for a long weekend :rage4:   

A database dump wouldn’t hurt if you’re not concerned with sharing it. Send that along to my email if you want to do that (or share here if you don’t mind posting it publicly).

**Comment by foxalerts23** [comment] 2021-01-02 17:21
@cdubz 
I'm running docker-compose using your [example](https://github.com/babybuddy/babybuddy/blob/master/docker-compose.example.yml) with variables filled in, nothing special (America/New_York).
I updated the docker images 2 days ago from 1.4.0 to 1.4.1.  Issue started after updating the images.  Worked immediately after the images were updated, stopped working maybe 16 hours later.  After reading @phooged post I just restarted the containers and the last feeding card is working correctly again.

BTW, thank you for creating such a great app, wife approval factor is very high!

**Comment by cdubz** [comment] 2021-01-02 17:35
Thanks for the additional info @foxalerts23. I do have some vague recollection of changes to the "time since" string handling between 1.4.0 and 1.4.1, I just haven't had a chance to dig in to the commit history.

I was actually just trying to reproduce this now but so far have not been able to. Weirdly, I can't seem to get the timezone or 24-hour environment variables to work via compose... this could just be some confusion from my lack of my Docker experience.

A database dump from an affected instance really would be helpful here if it could get to a repro situation quickly. Right now I'm just kind of winging it.

**Comment by phooged** [comment] 2021-01-02 18:38
@cdubz I'm willing to email you a database dumb, just not sure how... Kinda noob here. I can only export one category at a time?

I changed to 12h format and restarted, after about an hour the time since last changed back to 0 days.

When I look at the export of the last database entry it still showing in 24h format:

id,child_id,child_first_name,child_last_name,start,end,type,method,amount,notes
134,1,Sophia,(Last name),2021-01-02 19:00:00,2021-01-02 19:04:00,formula,bottle,60.0,
133,1,Sophia,(Last name),2021-01-02 18:25:00,2021-01-02 18:31:00,formula,bottle,140.0,

Cards are definitely in 12 hour format.

Hope this helps.

Tanks

**Comment by cdubz** [comment] 2021-01-02 19:27
Exporting from the app is probably not going to tell us much. Ideally we could get an export of the Postgres database itself. But I’m not sure how best to do that via Docker... I’ll have more of a chance to test stuff out in the next few days here.

What may still be helpful is if you could post your full Docker Compose file. Just to be sure, even if it is basically just the example config.

**Comment by cdubz** [comment] 2021-01-02 20:55
One other thing I just thought -- in both these examples did this start happening just after the new year? v1.4.1 has been out for six months now and those were the last substantial commits to the project. Seems like a long shot, but maybe this has something to do with entering a new year...

**Comment by foxalerts23** [comment] 2021-01-03 00:54
@cdubz 
I too don't know how to export from postgres.

This occurred before the new year (Dec 31, updated the images on Dec 30).

My docker-compose is below:

`version: "3.7"
services:
  db:
    image: postgres:11 # pin postgres to a major version
    environment:
      - PGDATA=/db-data
      - POSTGRES_PASSWORD=<variable> # has to correspond with POSTGRES_PASSWORD in APP
    restart: always
    volumes:
      - db:/db-data:rw
  app:
    image: babybuddy/babybuddy
    # See README.md#configuration for other environment configuration options.
    environment:
      - ALLOWED_HOSTS= localhost,127.0.0.1,::1,<host_IP>,<FQDN>
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.docker
      - SECRET_KEY=<variable>
      - TIME_ZONE=America/New_York
      - POSTGRES_PASSWORD=<variable>
      - DEBUG=False # Turn to False in production
    restart: always
    volumes:
      - media:/app/media:rw
    # Sleep 5 seconds to allow the db to to come up;
    command: bash -c 'sleep 5 && python manage.py migrate --noinput && python manage.py createcachetable && gunicorn babybuddy.wsg>
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db: {}
  media: {}`

**Comment by cdubz** [comment] 2021-01-03 01:16
Hmmmmm. I’m starting to wonder if maybe this has something to do with 389211de22444f749426b2258e27ed50b374e6b1. I think wonder if the slim variant is missing something for date time handling. I would expect it to fail more catastrophically though...

**Comment by phooged** [comment] 2021-01-03 07:59
`in both these examples did this start happening just after the new year?`
No, I installed on December the 18th, the problem started right from the beginning.

**Comment by cdubz** [comment] 2021-01-03 17:55
Thanks, @phooged. That timing could support my thinking re: the python slim base.

Another user has [reported this issue in Gitter](https://gitter.im/babybuddy/Lobby?at=5ff1e8d3ac9d8e7463ea2239) --

> im using the SQLite version and every so often the dashboard just shows last feeding and last diaper change as "0 days ago" instead of minutes or hours even though it could be just an hour ago. If i shutdown the docker image and bring it back up it seems to fix it self, just not sure why this is happening. I am using the admin account and I created a separate account for my wife, we both have our settings set to Central Time. I am not sure but i think it happens after we both add a feeding. Any ideas?

**Comment by ajishab** [comment] 2021-01-03 20:47
i just did some testing for me it seems to trigger right as soon as both me and wife enter an entry separately from our phones.  e.g. if enter a feeding it works fine up until my wife adds a feeding then it goes to 0 days.  i think it could be device related as i tried on my desktop logging in as me, adding an entry,  and then logging in as her and adding an entry, it did not seem to trigger that way.

both my wife and i are on iOS and using safari to access to app from our phones.  

restarting the docker container fixes the issue until we both add an entry again.

**Comment by cdubz** [comment] 2021-01-03 21:10
Thanks for the extra context, @ajishab.

> I just installed the app on the first btw.

Do you mean Dec 1? Have you updated the app since then or always seen this bug? That would hurt my theory about this potentially being caused somehow by 389211de22444f749426b2258e27ed50b374e6b1, which was committed 2 Dec.

**Comment by cdubz** [comment] 2021-01-03 21:21
Ah! I am able to reproduce! The culprit is actually 95a2cdf06dca56cfbf931927eca64edb02e2f657, which [monkey patches `timesince` chunks](https://github.com/babybuddy/babybuddy/commit/95a2cdf06dca56cfbf931927eca64edb02e2f657#diff-2439d77444f0be435d92d3e5df78ab2f065592d4f66c075a1bc92e1b8bb41954) for displaying a child's _age_ but then does not revert that change. Repro steps:

1. Log in to http://demo.baby-buddy.net/ (admin/admin)
2. Note that dashboard cards have times with hour/minute/second granularity.
3. Click on the child's name to go to the child's overview page.
4. Return to the dashboard.
5. Note most cards now say "0 days".

That was actually the first monkey patch I ever tried... so oops. I'll figure out some way to get this fixed and push a new release in the next day or two here.

Thanks @ajishab @phooged @foxalerts23 for all the help tracking this down.

**Comment by cdubz** [comment] 2021-01-04 03:08
This should be fixed on `master`. I'll also release `v1.5.0` soon with this fix included.

**Closed** 2021-01-04 03:08 UTC
Labels: bug
