### ISSUE TITLE
In Portuguese: events created from timers don't inherit times (start/end)

### ISSUE THREAD

**Issue by renatose** [babybuddy/babybuddy#532] opened 2022-09-22 21:58 UTC
This is a bug happening in Portuguese only as I tried changing to other languages and the function behaved as expected.
I'm using docker latest from linuxserver.io

**Comment by renatose** [comment] 2022-09-22 22:02
The issue is reproducible in the demo
http://demo.baby-buddy.net/

**Comment by cdubz** [comment] 2022-09-22 23:19
Probably related to or a duplicate of #498. It’s a nasty bug that I really need to dig in to…

**Comment by renatose** [comment] 2022-09-23 04:43
When my kid allows I'll try to dig into it as well and I'll post any findings.

**Comment by cdubz** [comment] 2023-02-12 01:43
Fixed by 1d9577a.

**Closed by cdubz** 2023-02-12 01:43 UTC
Labels: bug, i18n/L10n
