### ISSUE TITLE
Heroku Server Error (500)

### ISSUE THREAD

**Issue by johnnypea** [babybuddy/babybuddy#395] opened 2022-02-20 10:39 UTC
Deployed through Heroku button...

> Server Error (500)

```
2022-02-20T10:25:08.465271+00:00 app[web.1]: 10.1.24.253 - - [20/Feb/2022:11:25:08 +0100] "GET /login/?next=/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15"
2022-02-20T10:25:08.466689+00:00 heroku[router]: at=info method=GET path="/login/?next=/" host=xxx.herokuapp.com request_id=226bc97c-e841-487c-a02c-43f7a61cbd9c fwd="178.143.44.206" dyno=web.1 connect=0ms service=14ms status=500 bytes=486 protocol=https
```

Strangely, when I set `DEBUG=1` env var it works as expected and app runs.

**Comment by cdubz** [comment] 2022-02-20 21:59
I can't reproduce this currently -- could you try again? And if it still happens maybe post the Heroku build log? Not quite sure what else to check if it works with `DEBUG` set 🤔

**Comment by johnnypea** [comment] 2022-02-21 12:25
Still not working...

```
DATABASE_URL=postgres://XXX:YYY@ec2-ABC.eu-west-1.compute.amazonaws.com:5432/XYZ
DISABLE_COLLECTSTATIC=0
DJANGO_SETTINGS_MODULE=babybuddy.settings.heroku
SECRET_KEY=XXX
TIME_ZONE=Europe/Bratislava
```
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/python
-----> Python app detected
-----> Running pre-compile hook
-----> Using Python version specified in runtime.txt
 !     Python has released a security update! Please consider upgrading to python-3.9.10
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.9.9
-----> Installing pip 21.3.1, setuptools 57.5.0 and wheel 0.37.0
-----> Installing SQLite3
-----> Installing requirements with pip
       Looking in indexes: https://pypi.python.org/simple
       Collecting asgiref==3.5.0
         Downloading asgiref-3.5.0-py3-none-any.whl (22 kB)
       Collecting boto3==1.20.52
         Downloading boto3-1.20.52-py3-none-any.whl (131 kB)
       Collecting botocore==1.23.52
         Downloading botocore-1.23.52-py3-none-any.whl (8.5 MB)
       Collecting defusedxml==0.7.1
         Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
       Collecting diff-match-patch==20200713
         Downloading diff_match_patch-20200713-py3-none-any.whl (61 kB)
       Collecting dj-database-url==0.5.0
         Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
       Collecting django-appconf==1.0.5
         Downloading django_appconf-1.0.5-py3-none-any.whl (6.4 kB)
       Collecting django-axes==5.31.0
         Downloading django_axes-5.31.0-py3-none-any.whl (54 kB)
       Collecting django-filter==21.1
         Downloading django_filter-21.1-py3-none-any.whl (81 kB)
       Collecting django-imagekit==4.1.0
         Downloading django_imagekit-4.1.0-py2.py3-none-any.whl (43 kB)
       Collecting django-import-export==2.7.1
         Downloading django_import_export-2.7.1-py3-none-any.whl (100 kB)
       Collecting django-ipware==4.0.2
         Downloading django_ipware-4.0.2-py2.py3-none-any.whl (9.3 kB)
       Collecting django-storages==1.12.3
         Downloading django_storages-1.12.3-py3-none-any.whl (44 kB)
       Collecting django-widget-tweaks==1.4.12
         Downloading django_widget_tweaks-1.4.12-py3-none-any.whl (8.9 kB)
       Collecting django==4.0.2
         Downloading Django-4.0.2-py3-none-any.whl (8.0 MB)
       Collecting djangorestframework==3.13.1
         Downloading djangorestframework-3.13.1-py3-none-any.whl (958 kB)
       Collecting et-xmlfile==1.1.0
         Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
       Collecting faker==12.2.0
         Downloading Faker-12.2.0-py3-none-any.whl (1.5 MB)
       Collecting gunicorn==20.1.0
         Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
       Collecting jmespath==0.10.0
         Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
       Collecting markuppy==1.14
         Downloading MarkupPy-1.14.tar.gz (6.8 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting odfpy==1.4.1
         Downloading odfpy-1.4.1.tar.gz (717 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting openpyxl==3.0.9
         Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
       Collecting pilkit==2.0
         Downloading pilkit-2.0.tar.gz (161 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting pillow==9.0.1
         Downloading Pillow-9.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
       Collecting plotly==5.6.0
         Downloading plotly-5.6.0-py2.py3-none-any.whl (27.7 MB)
       Collecting psycopg2-binary==2.9.3
         Downloading psycopg2_binary-2.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
       Collecting python-dateutil==2.8.2
         Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
       Collecting python-dotenv==0.19.2
         Downloading python_dotenv-0.19.2-py2.py3-none-any.whl (17 kB)
       Collecting pytz==2021.3
         Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
       Collecting pyyaml==6.0
         Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
       Collecting s3transfer==0.5.1
         Downloading s3transfer-0.5.1-py3-none-any.whl (79 kB)
       Collecting setuptools==60.8.2
         Downloading setuptools-60.8.2-py3-none-any.whl (1.1 MB)
       Collecting six==1.16.0
         Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
       Collecting sqlparse==0.4.2
         Downloading sqlparse-0.4.2-py3-none-any.whl (42 kB)
       Collecting tablib[html,ods,xls,xlsx,yaml]==3.2.0
         Downloading tablib-3.2.0-py3-none-any.whl (48 kB)
       Collecting tenacity==8.0.1
         Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
       Collecting uritemplate==4.1.1
         Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
       Collecting urllib3==1.26.8
         Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
       Collecting whitenoise==6.0.0
         Downloading whitenoise-6.0.0-py3-none-any.whl (19 kB)
       Collecting xlrd==2.0.1
         Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
       Collecting xlwt==1.3.0
         Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
       Building wheels for collected packages: markuppy, odfpy, pilkit
         Building wheel for markuppy (setup.py): started
         Building wheel for markuppy (setup.py): finished with status 'done'
         Created wheel for markuppy: filename=MarkupPy-1.14-py3-none-any.whl size=7413 sha256=e6f18a26d17f80e51b67fb691b7bf351f2ebdf2130c17600ab8ec13dba75f5a9
         Stored in directory: /tmp/pip-ephem-wheel-cache-kp43igf0/wheels/ae/2b/4e/473f5e2321bbec46cf2dba49e58edb8f6482aa748790524f2a
         Building wheel for odfpy (setup.py): started
         Building wheel for odfpy (setup.py): finished with status 'done'
         Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=160693 sha256=7990f2c504837a45329b4688e4caad993d70779cc5cdfcfb026a8a3c27bd8fcd
         Stored in directory: /tmp/pip-ephem-wheel-cache-kp43igf0/wheels/20/ff/69/1b3f423ffe400b87afa368c70b43d2b5cd3bfb9ac8a613ba5b
         Building wheel for pilkit (setup.py): started
         Building wheel for pilkit (setup.py): finished with status 'done'
         Created wheel for pilkit: filename=pilkit-2.0-py3-none-any.whl size=18314 sha256=66741cd0f2174d4785875cfc93b2f4000625a3d54bacb3e4eaf4b2607bcad99f
         Stored in directory: /tmp/pip-ephem-wheel-cache-kp43igf0/wheels/7f/fc/22/47ed5e97488171d76b0d80db9c67272d42607debfdaaa50314
       Successfully built markuppy odfpy pilkit
       Installing collected packages: six, urllib3, sqlparse, python-dateutil, jmespath, et-xmlfile, defusedxml, asgiref, xlwt, xlrd, tablib, pyyaml, openpyxl, odfpy, markuppy, django, botocore, tenacity, setuptools, s3transfer, pytz, pilkit, django-ipware, django-appconf, diff-match-patch, whitenoise, uritemplate, python-dotenv, psycopg2-binary, plotly, pillow, gunicorn, faker, djangorestframework, django-widget-tweaks, django-storages, django-import-export, django-imagekit, django-filter, django-axes, dj-database-url, boto3
         Attempting uninstall: setuptools
           Found existing installation: setuptools 57.5.0
           Uninstalling setuptools-57.5.0:
             Successfully uninstalled setuptools-57.5.0
       Successfully installed asgiref-3.5.0 boto3-1.20.52 botocore-1.23.52 defusedxml-0.7.1 diff-match-patch-20200713 dj-database-url-0.5.0 django-4.0.2 django-appconf-1.0.5 django-axes-5.31.0 django-filter-21.1 django-imagekit-4.1.0 django-import-export-2.7.1 django-ipware-4.0.2 django-storages-1.12.3 django-widget-tweaks-1.4.12 djangorestframework-3.13.1 et-xmlfile-1.1.0 faker-12.2.0 gunicorn-20.1.0 jmespath-0.10.0 markuppy-1.14 odfpy-1.4.1 openpyxl-3.0.9 pilkit-2.0 pillow-9.0.1 plotly-5.6.0 psycopg2-binary-2.9.3 python-dateutil-2.8.2 python-dotenv-0.19.2 pytz-2021.3 pyyaml-6.0 s3transfer-0.5.1 setuptools-60.8.2 six-1.16.0 sqlparse-0.4.2 tablib-3.2.0 tenacity-8.0.1 uritemplate-4.1.1 urllib3-1.26.8 whitenoise-6.0.0 xlrd-2.0.1 xlwt-1.3.0
-----> $ python manage.py collectstatic --noinput
       163 static files copied to '/tmp/build_32fc6f84/static', 421 post-processed.
-----> Discovering process types
       Procfile declares types -> release, web
-----> Compressing...
       Done: 125.1M
-----> Launching...
 !     Release command declared: this new release will not be available until the command succeeds.
       Released v6
       https://xxx-buddy.herokuapp.com/ deployed to Heroku
```

```
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying axes.0001_initial... OK
  Applying axes.0002_auto_20151217_2044... OK
  Applying axes.0003_auto_20160322_0929... OK
  Applying axes.0004_auto_20181024_1538... OK
  Applying axes.0005_remove_accessattempt_trusted... OK
  Applying axes.0006_remove_accesslog_trusted... OK
  Applying axes.0007_alter_accessattempt_unique_together... OK
  Applying babybuddy.0001_initial... OK
  Applying babybuddy.0002_add_settings... OK
  Applying babybuddy.0003_add_refresh_help_text... OK
  Applying babybuddy.0004_settings_language... OK
  Applying babybuddy.0005_auto_20190502_1701... OK
  Applying babybuddy.0006_auto_20190502_1744... OK
  Applying babybuddy.0007_auto_20190607_1422... OK
  Applying babybuddy.0008_auto_20200120_0622... OK
  Applying babybuddy.0009_settings_timezone... OK
  Applying babybuddy.0010_auto_20200609_0649... OK
  Applying babybuddy.0011_auto_20200813_0238... OK
  Applying babybuddy.0012_auto_20201024_1847... OK
  Applying babybuddy.0013_auto_20210411_1241... OK
  Applying babybuddy.0014_settings_hide_empty... OK
  Applying babybuddy.0015_alter_settings_timezone... OK
  Applying babybuddy.0016_alter_settings_timezone... OK
  Applying babybuddy.0017_settings_hide_age... OK
  Applying babybuddy.0018_auto_20211017_2136... OK
  Applying babybuddy.0019_alter_settings_timezone... OK
  Applying babybuddy.0020_update_language_en_to_en_us... OK
  Applying core.0001_initial... OK
  Applying core.0002_auto_20171028_1257... OK
  Applying core.0003_weight... OK
  Applying core.0004_child_picture... OK
  Applying core.0005_auto_20190416_2048... OK
  Applying core.0006_auto_20190502_1701... OK
  Applying core.0007_temperature... OK
  Applying core.0008_auto_20190607_1422... OK
  Applying core.0009_diaperchange_amount... OK
  Applying core.0010_timer_child... OK
  Applying core.0011_auto_20200214_1939... OK
  Applying core.0012_auto_20200813_0238... OK
  Applying core.0013_auto_20210415_0528... OK
  Applying core.0014_alter_child_slug... OK
  Applying core.0015_add_nap_field_for_sleep... OK
  Applying core.0016_alter_sleep_napping... OK
  Applying core.0017_alter_child_last_name... OK
  Applying core.0018_bmi_headcircumference_height... OK
  Applying sessions.0001_initial... OK
```

`DEBUG` set to "true" makes it work.

**Comment by cdubz** [comment] 2022-02-21 12:47
Ah yeah ok. Collect static does need to be disabled because the static assets are included in the committed files. Last O checked Heroku doesn’t provide a good way to hide or disable changing that option in the button config. It’s an annoying bit of bad UX.

**Closed** 2022-02-21 16:32 UTC
Labels: need more info
