### ISSUE TITLE
Make error more helpful when entering conflicting/bad data

### ISSUE THREAD

**Issue by axelsimon** [babybuddy/babybuddy#542] opened 2022-10-13 15:19 UTC
If one enters by mistake say a feed from 11:30 AM to 11:50 **PM**, any attempt to add an extra feed within that time period will be met with a stern "Error 500". It's not obvious that the solution is as simple as correcting the time information.

Sometimes, Baby Buddy will tell you that this overlaps with another feed, but it doesn't seem to always be the case.

Is this a known problem?

**Comment by cdubz** [comment] 2022-10-13 15:41
> Sometimes, Baby Buddy will tell you that this overlaps with another feed, but it doesn't seem to always be the case.

Is should _always_ do that. I'm not able to reproduce a 500 for intersecting entries in the demo. Could you provide specific steps to reproduce?

**Comment by axelsimon** [comment] 2022-10-24 09:30
Agreed that this needs more info. I don't think i'm able to reproduce reliably yet, i think it has to do with the AM and PM toggle. (Which might be rendered moot when switching to #515 and using browser native datetime handling)

**Comment by cdubz** [comment] 2022-10-24 20:14
Ok, no worries. If this has been hitting you randomly and you can't get clear reproduction steps you could also try enabling debug mode (by setting the `DEBUG` environment variable to `1`) and the 500 error should give you a lot more details when it hits. I may be able to get some clues from that.

**Comment by cdubz** [comment] 2023-02-10 14:29
Closing this one out as stale but feel free to follow up if you are able to dig in and find more debugging info here.

**Comment by axelsimon** [comment] 2023-02-16 14:50
Sorry i dropped the ball on this. I will enable debug mode.

In the meantime, just got hit by this again: had a feed from 9:30 AM to 10:20 **PM** by mistake. Entering any feed after that intersect with that time interval just threw Error 500. This is on v1.13.2.

I'll try to reproduce with debug enabled.

**Comment by cdubz** [comment] 2023-05-08 01:52
I'm not able to reproduce this in v1.16.0 or upcoming v2.0.0-beta1 so closing again. But let me know if you do end up digging up more info.

**Closed by cdubz** 2023-05-08 01:52 UTC
Labels: need more info
